### ISSUE TITLE
[FEATURE] Autosurround 'DisableOnJump'

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#580] opened 2021-03-30 19:37 UTC
**What feature would you like to be added.**
An AutoSurround option to disable when you jump out of a hole.

**Comment by jumboman32** [comment] 2021-03-30 20:09
> pretty sure that “move” option is that

Move Delay is not the same.

**Comment by John200410** [comment] 2021-04-03 06:37
Duplicate of #306

**Closed by John200410** 2021-04-03 06:37 UTC
Labels: enhancement
