### ISSUE TITLE
Piston aura

### ISSUE THREAD

**Issue by UnknownAstronaut** [John200410/rusherhack-issues#606] opened 2021-04-08 21:35 UTC
**What feature would you like to be added.**
Piston aura

**Additional context**
Piston aura

**Comment by Mishi04** [comment] 2021-04-08 21:41
bruh

**Comment by RemainingToast** [comment] 2021-04-08 21:54
Who aura

**Comment by FluorideHistorian** [comment] 2021-04-09 00:01
duplicate issue

**Comment by ShaderTheBlackKid** [comment] 2021-04-09 03:52
Check the previous issues before making your own. Your not the only one who wants piston aura and duplicate issue

**Comment by obamagaming2069** [comment] 2021-04-09 15:44
piston aura user = enjoy the pipebomb in your mailbox soon

**Comment by Mishi04** [comment] 2021-04-09 16:04
> piston aura user = enjoy the pipebomb in your mailbox soon

^^^

**Comment by jumboman32** [comment] 2021-04-10 01:38
Reference #271

**Comment by tycrek** [comment] 2021-04-10 06:37
Duplicate of #271. There's a search bar people, use it.

**Closed** 2021-04-10 06:36 UTC
Labels: enhancement
