### ISSUE TITLE
[FEATURE] Autocast on autofish

### ISSUE THREAD

**Issue by ClassicalBlueTooth** [John200410/rusherhack-issues#900] opened 2021-07-02 21:38 UTC
**What feature would you like to be added.**
Have Autofish automatically cast the fishing rod once its equipped.

**Is your feature request related to a problem? Please describe.**
When playing on a server that restarts frequently (Constantiam) it'll restart and autofish will stop until you manually throw the rod again. It makes overnight afk fishing impossible as once you reconnect your char wont yeet the rod.

**Additional context**

**Comment by John200410** [comment] 2021-08-08 00:40
Duplicate of #425

**Closed by John200410** 2021-08-08 00:40 UTC
Labels: enhancement
