### ISSUE TITLE
[Search for Modules]

### ISSUE THREAD

**Issue by YeahOMA** [John200410/rusherhack-issues#351] opened 2021-01-14 02:53 UTC
I would like some sort of Search bar to be added to RusherHack as it is very hard to locate modules.

Basically whenever you search for a module the best suiting module will remain on the ClickGUI, all the modules that don't fit the search will dissapear. KAMIBlue has a search bar like this.

Sort of, it'll be much easier to search and find modules.

**Comment by browsky300** [comment] 2021-01-15 05:54
Yeah, this would be really useful. Just wondering, do you mean like a separate search bar as in inertia, or where you just type the name in and it highlights the modules, as in Impact?

**Comment by YeahOMA** [comment] 2021-01-15 14:11
Anything will be fine.

**Comment by browsky300** [comment] 2021-01-16 01:07
Nevermind, someone already suggested this feature and John will be adding it.
Duplicate of #251.

**Comment by John200410** [comment] 2021-01-21 22:17
Duplicate of #251

**Closed by John200410** 2021-01-21 22:17 UTC
Labels: enhancement
