### ISSUE TITLE
[FEATURE] Wireframe esp (while showing player skin)

### ISSUE THREAD

**Issue by gnq2b2t** [John200410/rusherhack-issues#613] opened 2021-04-10 22:32 UTC
When wireframe chams are on there should be a custom feature that allows the players skin to be showing while the wireframe is still there.

**Comment by jumboman32** [comment] 2021-04-11 03:32
Is this not just normal ESP?

**Comment by John200410** [comment] 2021-04-16 20:27
Duplicate of #180

**Closed by John200410** 2021-04-16 20:27 UTC
Labels: enhancement
