### ISSUE TITLE
[FEATURE] Addition to Better Chat

### ISSUE THREAD

**Issue by AiryXV** [John200410/rusherhack-issues#732] opened 2021-05-10 04:31 UTC
**What feature would you like to be added.**
www.curseforge.com/minecraft/mc-mods/better-chat/ 

Something like that , It provides a smooth animation of message incoming and outgoing /

**Is your feature request related to a problem? Please describe.**
No its not

**Additional context**
Example : https://youtu.be/SOqtHIBWwS0

**Comment by ProfKambing** [comment] 2021-05-10 07:50
just download it ffs

**Comment by AiryXV** [comment] 2021-05-12 04:12
it takes a bit of resources

**Comment by ProfKambing** [comment] 2021-05-12 06:32
huh, its the same when john adds it to rh

**Comment by jumboman32** [comment] 2021-07-06 19:40
Duplicate of #701

**Closed by jumboman32** 2021-07-06 19:40 UTC
Labels: enhancement, hud/ui, module-enhancement
