### ISSUE TITLE
[FEATURE] BedAura 

### ISSUE THREAD

**Issue by jam-in-a-jar** [John200410/rusherhack-issues#490] opened 2021-02-28 18:05 UTC
Bedaura
It is places beds automaticly and breaks and rotate and you arent kill at bedbombing or in bed pvp

It isnt a problem it is feature

Videos of Bedaura
https://www.youtube.com/watch?v=VRC0GZSIoCI&t=11s

**Comment by CaptainTheBeam** [comment] 2021-02-28 19:01
i think johns adding this in v1.2 since it was supposed to come in v1.1

**Comment by John200410** [comment] 2021-03-08 21:37
Duplicate of #8

**Closed by John200410** 2021-03-08 21:37 UTC
Labels: enhancement
