### ISSUE TITLE
Chest Swap

### ISSUE THREAD

**Issue by Neon273** [John200410/rusherhack-issues#860] opened 2021-06-10 23:56 UTC
Chest Swap that swaps chestplate for elytra when key bind is pressed
could be under AutoArmor module or just a new module

**Comment by ProfKambing** [comment] 2021-06-11 06:14
mf u could use macro

**Comment by fudge92** [comment] 2021-06-11 09:24
duplicate of #853

**Comment by fudge92** [comment] 2021-06-11 09:30
check #853  it will be much better, insteas of a keybind

**Comment by jumboman32** [comment] 2021-06-16 03:25
Closing in favor of #853, in the meantime use a macro with autoarmor elytrapriority.

**Closed by jumboman32** 2021-06-16 03:25 UTC
Labels: enhancement, invalid
