### ISSUE TITLE
[FEATURE] A setting to make the entity you're riding transparent

### ISSUE THREAD

**Issue by keepofthehause** [John200410/rusherhack-issues#852] opened 2021-06-07 06:08 UTC
**What feature would you like to be added.**
A setting for EntityControl that makes the entity you're on transparent so you can see what's below it

**Is your feature request related to a problem? Please describe.**
It's always a bit frustrating to ride an animal and have you and/or that animal die to something you couldn't see because the animal's a fatass.

**Comment by soham9229** [comment] 2021-06-07 07:19
Duplicate of #835

**Comment by keepofthehause** [comment] 2021-06-07 08:08
> If I am right, its Duplicate of #835

That suggests making it not render, this is just transparency

**Comment by jennifer-uwu** [comment] 2021-06-07 20:58
norender setting with transparancy slider? if you want to not see it at all you can move the slider up all the way

**Comment by jennifer-uwu** [comment] 2021-06-09 13:22
#835

**Closed by jennifer-uwu** 2021-06-09 13:22 UTC
Labels: enhancement
