### ISSUE TITLE
Customizable Discord RPC

### ISSUE THREAD

**Issue by Parrotry4197** [John200410/rusherhack-issues#711] opened 2021-05-02 03:39 UTC
**What feature would you like to be added.**
You should be able to pick from a few default options of customizations such as: server IP, coordinates, health, etc. You should also be able to set it as whatever you would type rather you have to do it in do it in the GUI or HUD editor or you have to do it in a file.

**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem. just a request.

**Additional context**
I have no screenshots or additional context.

**Comment by ItzDawnfall** [comment] 2021-05-02 04:40
Duplicate of #200

**Comment by jumboman32** [comment] 2021-05-02 14:51
Closing in favor of #200

**Closed** 2021-05-02 14:52 UTC
Labels: enhancement
