### ISSUE TITLE
City ESP[FEATURE]

### ISSUE THREAD

**Issue by 987654323456** [John200410/rusherhack-issues#58] opened 2020-10-26 20:54 UTC
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
This would show the obsidian that can be broken that could be used to city you. Would also show the blocks you can break to city other people. Option to color code.
**Is your feature request related to a problem? Please describe.**
no
**Additional context**

**Comment by John200410** [comment] 2020-10-26 21:00
Duplicate of #10

**Closed by John200410** 2020-10-26 21:00 UTC
Labels: duplicate, enhancement
