### ISSUE TITLE
[FEATURE] SwordGap in AutoTotem

### ISSUE THREAD

**Issue by end41r** [John200410/rusherhack-issues#787] opened 2021-05-22 12:07 UTC
[MODULE-ENHANCEMENT], 

work: if you are holding a sword, automatically change autototem (for example i have crystal) to gapple and when i switch sword to something else, autototem switches gapple back to crystal or whatever user wants

**Comment by jumboman32** [comment] 2021-05-22 12:11
Duplicate of #150

**Closed by jumboman32** 2021-05-22 12:11 UTC
Labels: enhancement
