### ISSUE TITLE
NoRender improvents 

### ISSUE THREAD

**Issue by SewerHatch** [John200410/rusherhack-issues#491] opened 2021-02-28 22:20 UTC
I suggest adding projectile NoRender (wither heads drop my fps from 300 to 5) and mobs NoRender (large amount of withers can crash my game lol)

**Comment by hashalite** [comment] 2021-03-01 08:38
Duplicate of [385](https://github.com/John200410/rusherhack-issues/issues/385)

**Comment by tycrek** [comment] 2021-03-05 00:36
Duplicate of #385

**Closed by tycrek** 2021-03-05 00:36 UTC
Labels: enhancement
