### ISSUE TITLE
[FEATURE] Until jump option for autosurround

### ISSUE THREAD

**Issue by tf2lover** [John200410/rusherhack-issues#499] opened 2021-03-03 19:37 UTC
**What feature would you like to be added.**
 A setting for autosurround that disables the module when you jump

**Is your feature request related to a problem? Please describe.**
Until move isn't ideal as I sometimes have to move about in a hole.

**Comment by jennifer-uwu** [comment] 2021-03-05 16:46
duplicate of https://github.com/John200410/rusherhack-issues/issues/306

**Closed** 2021-03-05 16:47 UTC
Labels: enhancement
