### ISSUE TITLE
[FEATURE] ExtraChest: Shulker Organizer

### ISSUE THREAD

**Issue by Infisrael** [John200410/rusherhack-issues#880] opened 2021-06-26 08:34 UTC
**What feature would you like to be added.**
Stash Organizer, organizes your shulkers in the chests
There will be 2 modes: Color & Name, Color will organize by color & Name by name of the shulker.

**Is your feature request related to a problem? Please describe.**
I am trying to move a stash, but the chest stealer module isn't always a good option, and I prefer to move the stash in the most efficient way.

**Additional context**
None.

**Comment by end41r** [comment] 2021-06-26 08:35
Really interesting idea

**Comment by HarryPotter42MC** [comment] 2021-06-28 08:47
just like Pyro StashSorter as refference

**Comment by jumboman32** [comment] 2021-06-28 15:03
Probably better as a seperate module and ExtraChest will be obsolete when the chest gui buttons are added.

**Comment by HarryPotter42MC** [comment] 2021-07-01 06:39
also maybe mode wich sees whats in there (dont know the name it would be called cos brain issue)

**Comment by Infisrael** [comment] 2021-07-01 17:38
> also maybe mode wich sees whats in there (dont know the name it would be called cos brain issue)

ExtraTooltips

**Comment by jumboman32** [comment] 2021-09-21 19:41
duplicate of #78

**Closed by jumboman32** 2021-09-21 19:41 UTC
Labels: enhancement, module
