### ISSUE TITLE
Step timer bug 2

### ISSUE THREAD

**Issue by ignelias** [John200410/rusherhack-issues#40] opened 2020-10-11 19:13 UTC
when you use 2 block step with timer on, timer stays on for about a second after you are done doing the 2 block step

**Comment by tycrek** [comment] 2020-10-11 19:20
Duplicate of #39

**Comment by ignelias** [comment] 2020-10-11 19:28
it's not

**Comment by John200410** [comment] 2020-10-11 20:52
It is indeed a duplicate of #39

**Closed by John200410** 2020-10-11 20:52 UTC

**Comment by John200410** [comment] 2020-10-11 20:53
Nevermind its not, but they should be combined instead of making two separate issues.

**Comment by John200410** [comment] 2020-10-12 02:15
This has been fixed in v1.1
