### ISSUE TITLE
dispensor a32k[FEATURE]

### ISSUE THREAD

**Issue by phobological** [John200410/rusherhack-issues#556] opened 2021-03-27 18:26 UTC
**What feature would you like to be added.**
Dispensor auto32k for servers with 32k meta like ECME and impurity.  examples: yakgod.cc, badlion+, bruce client, Impact+ and much more

**Is your feature request related to a problem? Please describe.**
No problem, jsut a request.

**Comment by FluorideHistorian** [comment] 2021-03-27 18:27
no

**Comment by phobological** [comment] 2021-03-27 18:28
> no

its an idea jesus

**Comment by FluorideHistorian** [comment] 2021-03-27 18:29
pretty sure this is either a duplicate issue or john doesnt want to add it

**Comment by dldlglglgluyl** [comment] 2021-03-27 18:39
lol

**Comment by Mishi04** [comment] 2021-03-27 20:11
duplicate of #19

**Closed** 2021-04-03 05:28 UTC
Labels: enhancement
