### ISSUE TITLE
[FEATURE] Speed HUD Element Average

### ISSUE THREAD

**Issue by jumboman32** [John200410/rusherhack-issues#848] opened 2021-06-06 17:27 UTC
**What feature would you like to be added.**
An average speed over a certain number of ticks/seconds to display instead of constantly updating.

**Is your feature request related to a problem? Please describe.**
Using certain travel methods gives an unclear speed that is going up and down.

**Comment by John200410** [comment] 2021-06-18 03:32
Duplicate of #372

**Closed by John200410** 2021-06-18 03:32 UTC
Labels: enhancement, module-enhancement, ui
