### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ur6jtrdjtdyjtdrjt3243253** [John200410/rusherhack-issues#891] opened 2021-06-30 14:30 UTC
**What feature would you like to be added.**
More variables for the "basefinder" module, like nether portals.

**Is your feature request related to a problem? Please describe.**
No

**Additional context**
I think this would be useful for afking in far out nether

**Comment by jumboman32** [comment] 2021-07-01 00:31
Duplicate of #81

**Closed by jumboman32** 2021-07-01 00:31 UTC
Labels: enhancement
