### ISSUE TITLE
[FEATURE] Allowed Cracked Accounts in the Alt Manager

### ISSUE THREAD

**Issue by robert40c** [John200410/rusherhack-issues#68] opened 2020-10-28 17:53 UTC
**What feature would you like to be added.**
Allowed Cracked Accounts in the Alt Manager

**Is your feature request related to a problem? Please describe.**
no

**Additional context**
yes

**Comment by John200410** [comment] 2020-10-28 22:10
Duplicate of #64

**Closed by John200410** 2020-10-28 22:10 UTC
Labels: duplicate, enhancement
