### ISSUE TITLE
[FEATURE] better packetfly phase

### ISSUE THREAD

**Issue by 278x** [John200410/rusherhack-issues#623] opened 2021-04-12 17:59 UTC
**What feature would you like to be added.**
better phase in packetfly

**Is your feature request related to a problem? Please describe.**
when i use packetfly it doesnt phase and kicks me when i try to long but moving around and going up works normally

**Additional context**

**Comment by ShaderTheBlackKid** [comment] 2021-04-12 19:37
Config issue probably

**Comment by 278x** [comment] 2021-04-12 22:20
i have tried every config doesnt work

**Comment by John200410** [comment] 2021-04-16 21:42
Duplicate of #221

**Closed by John200410** 2021-04-16 21:42 UTC
Labels: enhancement
