### ISSUE TITLE
[FEATURE] packetmine render changes

### ISSUE THREAD

**Issue by xxxcodestation1** [John200410/rusherhack-issues#594] opened 2021-04-04 17:05 UTC
When you packetmine a block and its ready to break make it render a diffrent color.

I think this is useful because i usually only swap to my pickaxe when a block is ready to break, and without an indication of when i can swap this is kind of difficult to guess.

**Comment by jumboman32** [comment] 2021-04-04 18:40
Duplicate of #579

**Comment by John200410** [comment] 2021-04-16 17:23
Duplicate of #579

**Closed by John200410** 2021-04-16 17:23 UTC
Labels: enhancement
