### ISSUE TITLE
Better rainbow rendering[FEATURE]

### ISSUE THREAD

**Issue by y4ndex1** [John200410/rusherhack-issues#381] opened 2021-01-24 08:31 UTC
https://i.imgur.com/cHl5dX1.png here is the example

more different rainbow rendering that looks cooler, next to 2 color hud elements would look awesome https://i.imgur.com/3DK0o6m.png

**Comment by John200410** [comment] 2021-01-24 21:47
Duplicate of #69

**Closed by John200410** 2021-01-24 21:47 UTC
Labels: enhancement
