### ISSUE TITLE
[FEATURE] account manager

### ISSUE THREAD

**Issue by Mishi04** [John200410/rusherhack-issues#523] opened 2021-03-12 16:29 UTC
**What feature would you like to be added.**
I think that rusherhack account manager needs an option for add cracked accounts same as pyro account manager

**Is your feature request related to a problem? Please describe.**
I play cracked servers with another nicknames and I need to use another launcher 

**Additional context**
N/A

**Comment by John200410** [comment] 2021-03-12 16:58
Duplicate of #64

**Closed by John200410** 2021-03-12 16:58 UTC
Labels: enhancement
