### ISSUE TITLE
[FEATURE] AutoCrystal > Placement > TerrainPlace

### ISSUE THREAD

**Issue by Lavacasted** [John200410/rusherhack-issues#1005] opened 2021-08-11 15:09 UTC
**What feature would you like to be added.**
A new feature for AC where it would autoplace obby at the best spot to cause damage to your target.

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
Would be cool if there was a module under TerrainPlace called PlaceBlockOnLiquid where its something like LiquidInteract but it autoplaces obby on top of liquid source blocks. Like when you are chasing someone in the overworld in an ocean biome or pvping in lava lakes. No need to toggle L.I and manually place obby.

**Comment by FluorideHistorian** [comment] 2022-07-17 18:44
duplicate of #628

**Closed by FluorideHistorian** 2022-07-17 18:44 UTC
Labels: enhancement
