### ISSUE TITLE
Auto Search Bar [FEATURE]

### ISSUE THREAD

**Issue by SilverEyes2b2t** [John200410/rusherhack-issues#861] opened 2021-06-11 21:53 UTC
**What feature would you like to be added.**

A add on to the Search Bar feature in the Click GUI. This add on would allow you to type instantly into the search bar  when opening your GUI without clicking on the search bar.

**Is your feature request related to a problem? Please describe.**
No, i am just a lazy bum who doesn't want to click on the search bar and I see other clients like Kami and Impact have it.

**Comment by jumboman32** [comment] 2021-06-16 03:24
Duplicate of #719

**Closed by jumboman32** 2021-06-16 03:24 UTC
Labels: enhancement
