### ISSUE TITLE
Add a module for disabling/enabling certain sounds

### ISSUE THREAD

**Issue by alucardontop** [John200410/rusherhack-issues#1317] opened 2022-06-27 09:49 UTC
I often want certain sounds (like the xp bottle broken sound to not be played, but collecting xp to be played)
Even if I just wanted anything xp sound related to be disabled, this still wouldn't be possible. I think it'd be very beneficial to add a module to let certain sounds be played and others to be disabled. The customization could go under the list where you edit packetlogger. 

Maybe this could be added by v1.3?

**Comment by quackitiy** [comment] 2022-07-01 16:06
you can already do this with resourcepacks using sounds.json, which goes in assets/minecraft.
 
heres a link to the default minecraft 1.12-1.14  sounds.json file,
https://gist.github.com/tryashtar/584d7aacd2f9aab28c7191d0bb5188d3
go crazy go wild

**Comment by browsky300** [comment] 2022-07-22 19:09
duplicate of #1079

**Closed by browsky300** 2022-07-22 19:09 UTC
Labels: enhancement
