### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by GentleWither** [John200410/rusherhack-issues#545] opened 2021-03-22 12:17 UTC
**What feature would you like to be added.**
TargetHud And Radar

**Is your feature request related to a problem? Please describe.**
no probs

**Additional context**
make a targetHud like in pyro that ill be cool to add

**Comment by ProfKambing** [comment] 2021-03-23 00:15
esp - 2d (thats radar)

https://github.com/John200410/rusherhack-issues/issues/360

**Comment by Mishi04** [comment] 2021-03-23 06:51
What advantage does this give over just using Nametags?

**Comment by John200410** [comment] 2021-03-23 17:13
Duplicate of #240

**Closed by John200410** 2021-03-23 17:13 UTC
Labels: enhancement
