### ISSUE TITLE
[FEATURE] Minimap

### ISSUE THREAD

**Issue by defineddank** [John200410/rusherhack-issues#1325] opened 2022-07-19 22:59 UTC
**What feature would you like to be added.**
A minimap option in the GUI manager that adds a circular minimap on the screen

**Is your feature request related to a problem? Please describe.**
No

**Additional context**
![rushersuggest](https://user-images.githubusercontent.com/62781865/179862170-8bd6a0e6-c77d-41b9-8712-0a48c6461c18.jpeg)

**Comment by Ozynt** [comment] 2022-07-19 23:01
Duplicate of #240

**Closed by Ozynt** 2022-07-19 23:01 UTC
Labels: enhancement
