### ISSUE TITLE
Search tracer range[FEATURE]

### ISSUE THREAD

**Issue by kyle5283** [John200410/rusherhack-issues#1244] opened 2022-02-27 15:57 UTC
Search module tracer option should have a range setting to increase the distance at which tracers are drawn. 
For example, with ESP enabled, I can see a chest long before a tracer is drawn to it, even with the search range set to 500 (the maximum)

My brother uses Impact, and is side by side testing, as soon as impact sees a storage on ESP, a tracer is drawn. I can see the same storage on ESP the same time he can, but I must get much closer before a tracer appears. This means I could be flying looking for a base and miss something underground because the tracers are simply never drawn to the objects. Sometimes even if I am very close to the chest, the tracers will not appear, but I can make them appear by simply toggling freecam on and off. Once drawn, the tracers will stay on the screen until the chest goes out of ESP range, but getting them to show up requires being quite close.

**Comment by nossravgni** [comment] 2022-03-04 14:56
I've had the same problem

**Comment by John200410** [comment] 2022-03-28 00:09
Duplicate of #1145

**Closed by John200410** 2022-03-28 00:09 UTC
Labels: enhancement
