### ISSUE TITLE
[FEATURE] packet mine queue

### ISSUE THREAD

**Issue by NeKaersh** [John200410/rusherhack-issues#1053] opened 2021-09-11 19:15 UTC
Add a module repeat and queue module to the PacketMine module. Repeats - breaks the block if it was placed. Queue - adds the ability to specify a large number of blocks, and they all break in turn.

**Comment by jumboman32** [comment] 2021-09-21 19:39
duplicate of #915

**Closed by jumboman32** 2021-09-21 19:39 UTC
Labels: enhancement
