### ISSUE TITLE
[FEATURE] Add Blacklisted players in friend manager

### ISSUE THREAD

**Issue by Floppinqq** [John200410/rusherhack-issues#293] opened 2021-01-02 14:55 UTC
you should add Enemy/Blacklisted player in friend manager, what will happen:
if you're in combat with a normal player, the ca will be normally, but if a blacklisted player appears, the ca will change the target to the blacklisted player and ignore the another (you can change this if you want)

the blacklisted player will have a red name and red esp whatever and if possible add a chat message like: [rusherhack] <blacklistedplayername> is near you

or anything

and if possible too, add a toast notification in desktop when the blacklisted player joined in your vision field

;)

**Comment by John200410** [comment] 2021-01-04 05:50
Duplicate of #122

**Closed by John200410** 2021-01-04 05:50 UTC
Labels: enhancement
