### ISSUE TITLE
[FEATURE] better xray

### ISSUE THREAD

**Issue by racoonersssss** [John200410/rusherhack-issues#362] opened 2021-01-17 09:57 UTC
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
**i think that xray needs a little extra and you should make it so you can see the blocks around you but see through them like tone down there transparency **

**Additional context**

**Comment by John200410** [comment] 2021-01-24 20:10
Duplicate of #104

**Closed by John200410** 2021-01-24 20:10 UTC
Labels: enhancement
