### ISSUE TITLE
[BUG] Tunnel ESP adapts blockoutline thickness when aiming at a block

### ISSUE THREAD

**Issue by HarryPotter42MC** [John200410/rusherhack-issues#1032] opened 2021-09-04 11:28 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/82435253/132092817-86425aa2-8764-4ba8-be14-e92c8f439291.png)
This config
not looking at block OR blockoutline disabled
![image](https://user-images.githubusercontent.com/82435253/132092839-15e9e731-702a-46ec-9db8-046a6dfda90b.png)
looking at a block with blockoutline enabled
![image](https://user-images.githubusercontent.com/82435253/132092848-267786be-3b4f-4e39-895c-034e6b50d3f2.png)
only affects when the block is in reach

**To Reproduce**
^shown above

**Other mods**
future

**Expected behavior**
thickness should stay the same

**Screenshots**
^above

**Additional context**
nah

**Comment by John200410** [comment] 2021-09-04 14:19
Unable to reproduce:
![image](https://user-images.githubusercontent.com/43681932/132097612-00538db8-9202-456a-ba79-9b86e7e65531.png)
![image](https://user-images.githubusercontent.com/43681932/132097620-d2689eae-f863-4cbe-8b60-7cd370e90a0c.png)

Do you have any other mods?

**Comment by John200410** [comment] 2021-09-04 14:21
Even though I am unable to reproduce, I forgot to make thickness customizable anyway. So in the next update it should be fixed.

**Closed by John200410** 2021-09-04 14:21 UTC
Labels: bug, will-fix
