### ISSUE TITLE
[FEATURE] Packet Fast Break Enhancements

### ISSUE THREAD

**Issue by Lempity** [John200410/rusherhack-issues#608] opened 2021-04-09 15:10 UTC
**What feature would you like to be added.**
Add it so when you can insta break a block with packet fastbreak the render turns green

**Is your feature request related to a problem? Please describe.**
Request

**Additional context**
![2021-04-09_10 09 58](https://user-images.githubusercontent.com/71273838/114201468-d57f7980-991b-11eb-8ee4-cce9ebd30336.png)

**Comment by Mishi04** [comment] 2021-04-09 15:18
This has been added in the next update

**Comment by ShaderTheBlackKid** [comment] 2021-04-09 17:47
Ffs read the previous issues since this is already added

**Comment by jumboman32** [comment] 2021-04-10 01:36
Duplicate of #579

**Comment by John200410** [comment] 2021-04-16 17:34
Duplicate of #579

**Closed by John200410** 2021-04-16 17:34 UTC
Labels: enhancement
