### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by RemainingToast** [John200410/rusherhack-issues#557] opened 2021-03-28 02:49 UTC
**What feature would you like to be added.**
Replace HideCommon in Packet Logger with customisable whitelist

**Is your feature request related to a problem? Please describe.**
Whitelist feature to PacketLogger to add your own packets to ignore into PacketLogger

**Additional context**
Yeet

**Comment by John200410** [comment] 2021-04-03 05:29
Duplicate of #502

**Closed by John200410** 2021-04-03 05:29 UTC
Labels: enhancement
