### ISSUE TITLE
[FEATURE] AutoEat (BoatFly mode)

### ISSUE THREAD

**Issue by rockeZZergon** [John200410/rusherhack-issues#120] opened 2020-11-06 22:50 UTC
Rusherhack+ allows you moving kinda fast and even through blocks using phase.
But unfortunately, you can't use any items while you moving on boat. But once you stopped move and turned off AutoWalk (in another client) or stopped holding "W" key, you could interact with everything. Its vanilla feature.
So my suggestion is add "Boatfly mode" in AutoEat, so once you have to eat anything to regenerate yourself, your boat will stop moving for a while, and after you ate, you continue moving.

**Comment by John200410** [comment] 2020-11-06 23:04
Duplicate of #109

**Closed by John200410** 2020-11-06 23:04 UTC
Labels: duplicate
