### ISSUE TITLE
[FEATURE] Add a disable on jump option to AutoSurround

### ISSUE THREAD

**Issue by pcpxd** [John200410/rusherhack-issues#315] opened 2021-01-05 23:56 UTC
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by John200410** [comment] 2021-01-11 05:13
Duplicate of #306

**Closed by John200410** 2021-01-11 05:13 UTC
Labels: duplicate, enhancement
