### ISSUE TITLE
[FEATURE] Bring back displaying other players potion effects on nametags

### ISSUE THREAD

**Issue by nwop1** [John200410/rusherhack-issues#1036] opened 2021-09-05 19:51 UTC
**What feature would you like to be added.**
Just like how it used to be pre b11 I think, an option to show other peoples potion effects under nametags like this video: https://www.youtube.com/watch?v=zF384Ws4Vgc (For some reason on other clients, the potion effects dont update if an effect is added or removed until you reload chunks or leave render distance but there is probably a fix for that? Besides that it used to be really nice)

**Is your feature request related to a problem? Please describe.**
Problem is that it was removed from rusherhack and I really liked it for oldfag pvp :(

**Additional context**
Pretty straightforward I don't have anything else to say.

**Comment by jennifer-uwu** [comment] 2021-09-07 19:07
duplicate of #743

**Closed by jennifer-uwu** 2021-09-07 19:07 UTC
Labels: enhancement
