### ISSUE TITLE
[FEATURE] EntityList Friends/Enemies

### ISSUE THREAD

**Issue by ItzDawnfall** [John200410/rusherhack-issues#632] opened 2021-04-13 02:42 UTC
**What feature would you like to be added.**
Have a setting under EntityList that shows friended/enemy users in the colors set in Colors.

**Comment by jumboman32** [comment] 2021-04-13 02:46
Duplicate of #598

**Comment by ItzDawnfall** [comment] 2021-04-13 02:54
> Duplicate of #598

My bad, I'll close this one

**Closed** 2021-04-13 02:54 UTC
Labels: enhancement
