### ISSUE TITLE
[FEATURE] Cbook

### ISSUE THREAD

**Issue by ElectricplaysGaming** [John200410/rusherhack-issues#1231] opened 2022-02-18 14:24 UTC
**Cbook Command.**
A detailed explanation of what this feature should be.
Just like in inertia how you can do a command ".Cbook random <number>", it would fill the book with random unicodes which causes dupes and book bans

**Comment by HausemasterIssue** [comment] 2022-02-18 20:00
There is a pastebin by EarthComputer with a bunch of unicode characters for each page of a book: https://pastebin.com/kREVWL4b

**Comment by John200410** [comment] 2022-02-20 15:32
Duplicate of #361

**Closed by John200410** 2022-02-20 15:32 UTC
Labels: enhancement
