### ISSUE TITLE
[FEATURE] HoleHP setting for AutoTotem

### ISSUE THREAD

**Issue by MrHakan** [John200410/rusherhack-issues#762] opened 2021-05-16 00:56 UTC
add HoleHP setting for AutoTotem Health mode

**Comment by ProfKambing** [comment] 2021-05-16 01:15
this is already suggested

**Comment by ProfKambing** [comment] 2021-05-16 01:16
https://github.com/John200410/rusherhack-issues/issues/468

**Comment by jumboman32** [comment] 2021-05-24 09:26
Duplicate of #468

**Closed** 2021-05-24 09:27 UTC
Labels: enhancement
