### ISSUE TITLE
[FEATURE] RIGHT CLICK GAP

### ISSUE THREAD

**Issue by ProfKambing** [John200410/rusherhack-issues#649] opened 2021-04-15 14:39 UTC
Offhand right click gap when u have a sword in mainhand

**Comment by tycrek** [comment] 2021-04-15 19:47
Did you mean "AutoEat should work with gaps in offhand"? Because that's a bug I've had

**Comment by jumboman32** [comment] 2021-04-16 14:10
He wants offhand to switch to a golden apple while you are holding a sword with packeteat so you can just right click once to eat. (i think)

**Comment by ProfKambing** [comment] 2021-04-18 00:51
no packeteat, i just want offhand improvement

**Comment by tycrek** [comment] 2021-04-18 01:04
Like what? "improvement" isn't helpful, what *specifically* do you want improved?

**Comment by ProfKambing** [comment] 2021-04-18 01:07
offhand gap when sword in mainhand, default item, no hotbar, right click gap, fall distance. like salhack, konas, and gamesense. those are the clients that have good offhand

**Comment by RemainingToast** [comment] 2021-04-18 01:08
Whilst right clicking with a sword swap to a golden apple and swap back once right click is released

**Comment by ProfKambing** [comment] 2021-04-18 01:08
^

**Comment by John200410** [comment] 2021-04-19 00:22
Duplicate of #409

**Closed by John200410** 2021-04-19 00:22 UTC
Labels: enhancement
