### ISSUE TITLE
[FEATURE] Color Sync

### ISSUE THREAD

**Issue by Infisrael** [John200410/rusherhack-issues#1163] opened 2021-12-18 11:15 UTC
**What feature would you like to be added.**
Color sync for hud elements, so you pick a color and it syncs with the other hud elements colors

**Is your feature request related to a problem? Please describe.**
1 color for every hud element looks clean to me and I can't be asked to do it manually for each one.

**Comment by wce2005a** [comment] 2021-12-18 16:44
yes pls

**Comment by John200410** [comment] 2021-12-18 19:35
Duplicate of #63

**Closed by John200410** 2021-12-18 19:35 UTC
Labels: enhancement
