### ISSUE TITLE
[FEATURE] More Chams Options

### ISSUE THREAD

**Issue by Lempity** [John200410/rusherhack-issues#604] opened 2021-04-06 14:46 UTC
**What feature would you like to be added.**
Also having held items option for chams
**Is your feature request related to a problem? Please describe.**
None of the white held item chams.
**Additional context**
![2021-04-06_09 44 17](https://user-images.githubusercontent.com/71273838/113729821-fa29e600-96bc-11eb-906b-43c2abed1e75.png)

**Comment by jumboman32** [comment] 2021-04-10 01:40
Similar to #43

**Comment by John200410** [comment] 2021-04-16 17:30
Duplicate of #369

**Closed by John200410** 2021-04-16 17:30 UTC
Labels: enhancement
