### ISSUE TITLE
[FEATURE] RADAR

### ISSUE THREAD

**Issue by Bulwharks** [John200410/rusherhack-issues#1044] opened 2021-09-08 00:19 UTC
**What feature would you like to be added.**
I think that a radar feature would be a great addition. A radar that shows North, East, South, and West. It could also show where entities are that are shown with tracers and an option to also show the entities that are within your distance for each that you have selected.

**Is your feature request related to a problem? Please describe.**
My request is not related to a specific problem, but i think that it would be beneficial and make movement in areas and seeing where entities are without having to turn and see where exactly a tracer is landing.

**Additional context**
N/A

**Comment by jumboman32** [comment] 2021-09-08 00:20
Duplicate of #240

**Closed by jumboman32** 2021-09-08 00:20 UTC
Labels: enhancement
