### ISSUE TITLE
Basefinder logs spawner chests

### ISSUE THREAD

**Issue by UnknownAstronaut** [John200410/rusherhack-issues#567] opened 2021-03-28 16:03 UTC
Basefinder logs dungeon chests. I have 10 chest setting but i still get notifications even spawner chests are in different chunks. Kami's stashlogger is much smarter.

**Comment by jumboman32** [comment] 2021-03-29 13:34
You will find a lot of dungeons near each other, and there is nothing you can do about world generation. Raise the chest limit.

**Comment by jumboman32** [comment] 2021-03-29 13:35
and duplicate of #565

**Comment by John200410** [comment] 2021-04-03 06:18
Duplicate of #81

**Closed by John200410** 2021-04-03 06:18 UTC
Labels: bug
