### ISSUE TITLE
[FEATURE] Entity jesus. Allow horses to walk on water.

### ISSUE THREAD

**Issue by Hiiva** [John200410/rusherhack-issues#279] opened 2020-12-28 18:37 UTC
**What feature would you like to be added.**
Entity jesus. Allow horses to walk on water.

**Is your feature request related to a problem? Please describe.**
Impact has it working, so should rh.

**Additional context**

**Comment by John200410** [comment] 2020-12-28 20:30
Duplicate of #128

**Closed by John200410** 2020-12-28 20:30 UTC
Labels: enhancement
