### ISSUE TITLE
[BUG] Absorption Hearts Invisible in Freecam

### ISSUE THREAD

**Issue by hashalite** [John200410/rusherhack-issues#445] opened 2021-02-11 01:55 UTC
**Describe the bug**
When freecam is enabled absorption hearts don't render.

**To Reproduce**
1. Eat gapple
2. Freecam

**Other mods**
none

**Comment by tycrek** [comment] 2021-02-14 16:27
duplicate of #439

**Comment by hashalite** [comment] 2021-02-14 17:35
That issue was only talking about a bug with AutoEat before it was renamed. If the two bugs are related, I guess it would make sense to merge them, but I figured they should get separate issues if not.

**Comment by tycrek** [comment] 2021-02-14 19:12
> 
> 
> That issue was only talking about a bug with AutoEat before it was renamed. If the two bugs are related, I guess it would make sense to merge them, but I figured they should get separate issues if not.

oh woops my bad, read that issue wrong. thanks for pointing that out

**Comment by John200410** [comment] 2021-02-18 04:04
Thank you for reporting this.

**Comment by John200410** [comment] 2021-02-19 03:46
This has been fixed in the next update.

**Closed by John200410** 2021-02-19 03:46 UTC
Labels: bug, will-fix
