### ISSUE TITLE
[FEATURE] in-game Time HUD

### ISSUE THREAD

**Issue by tycrek** [John200410/rusherhack-issues#517] opened 2021-03-11 02:13 UTC
**What feature would you like to be added.**
Show in-game time as a HUD module. It's based around current day tick or something iirc

**Additional context**
If possible I'd like to see both system time and in-game world time as separate HUD modules.

**Comment by John200410** [comment] 2021-03-23 16:13
Thank you for the suggestion. What do you think the name of the hud element should be?

**Comment by tycrek** [comment] 2021-03-23 16:14
WorldTime or ServerTime maybe?

**Comment by jumboman32** [comment] 2021-04-22 14:30
Duplicate of #193

**Closed** 2021-05-24 15:52 UTC
Labels: enhancement, will-add
