### ISSUE TITLE
[BUG] Speed Config Save

### ISSUE THREAD

**Issue by HeXaNi** [John200410/rusherhack-issues#176] opened 2020-11-26 22:13 UTC
**Describe the bug**
When restarting the game, the entire config for speed besides enabled or disabled is reset.
**To Reproduce**
Change some settings for speed
Restart game
**Other mods**
List other forge mods you are using (if any):
Optifine & Baritone
**Expected behavior**
Restarting the game would still keep my hotkey and settings for speed.
**Screenshots**

**Additional context**

**Comment by John200410** [comment] 2020-12-15 22:14
I have found the cause of this. Working on a fix now.

**Comment by John200410** [comment] 2020-12-15 22:14
This has been fixed and will be in a silent patch today.

**Closed by John200410** 2020-12-15 22:14 UTC
Labels: bug, will-fix
