### ISSUE TITLE
Basefinder is not effective

### ISSUE THREAD

**Issue by UnknownAstronaut** [John200410/rusherhack-issues#565] opened 2021-03-28 15:36 UTC
Basefinder returns on the same place often, 

Pls opimize the algotithm not stuck on the same 1k 1k square.

**Other mods**
kami, cause elytrafly is better

**Expected behavior**
Visit every chunk just once

**Comment by John200410** [comment] 2021-04-03 06:10
Duplicate of #274

**Closed by John200410** 2021-04-03 06:10 UTC
Labels: bug
