### ISSUE TITLE
crystal/totem number

### ISSUE THREAD

**Issue by nirosgalactic** [John200410/rusherhack-issues#1247] opened 2022-03-02 18:31 UTC
it is a module that as said in the name counts and displays how many totems, crystals, obsidian blocks are in your inventory, lambda curently has this in its hud editor and it would be really usefull in cpvp, or can be set to whatever the user needs it would also be usefull when building since alot of hotbar replenish modules leave a bunch of half used stacks in the inventory

**Comment by Ozynt** [comment] 2022-03-02 18:50
duplicate of #712

**Closed by Ozynt** 2022-03-02 18:50 UTC
Labels: enhancement
