### ISSUE TITLE
[BUG] alternatewhen  in autototem doesnt work

### ISSUE THREAD

**Issue by SoggyBacco** [John200410/rusherhack-issues#1250] opened 2022-03-06 23:28 UTC
alternatewhen doesnt have any effect on your offhand switching when it should make autototem only swap to crystals when ca is on

i remember this working with the old ca so it was probably never updated to work with the rewritten ca

**Comment by John200410** [comment] 2022-03-07 00:58
What are your AutoTotem settings?

**Comment by SoggyBacco** [comment] 2022-03-07 09:29
mode: health
hp: 16
absorbtioncheck
alternateitem: crystal
alternatewhen/requiresautocrystal
falldist: 20
delay:0
inv/hotbarprio/eating

it still holds crystals when ca is off

**Comment by John200410** [comment] 2022-03-09 02:59
Can you please record a video?

**Comment by SoggyBacco** [comment] 2022-03-09 09:22
first half is what alternatewhen should do based on my cfg, second half is what it actually does

https://user-images.githubusercontent.com/76087383/157411642-9b6f2a2f-2492-4411-95b0-5ab2bdec6088.mp4

**Comment by FluorideHistorian** [comment] 2022-07-17 18:57
duplicate of #1048

**Closed by FluorideHistorian** 2022-07-17 18:57 UTC
Labels: bug
