### ISSUE TITLE
[FEATURE] Increase scaffold width

### ISSUE THREAD

**Issue by Chiwarn** [John200410/rusherhack-issues#881] opened 2021-06-26 17:25 UTC
When scaffolding, instead of strictly one block below you, you can choose up to 5 blocks wide. This will be good for constructing floors or celings quickly.

**Comment by end41r** [comment] 2021-06-26 17:26
Yes but this will prob work only in singleplayer, because most of servers have anticheats and they won't allow smth like this

**Comment by Chiwarn** [comment] 2021-06-26 17:35
> Yes but this will prob work only in singleplayer, because most of servers have anticheats and they won't allow smth like this

I've seen other clients do it on 2bt2, it is okay if it needs to individually place the blocks

**Comment by end41r** [comment] 2021-06-26 17:36
> > Yes but this will prob work only in singleplayer, because most of servers have anticheats and they won't allow smth like this
> 
> I've seen other clients do it on 2bt2, it is okay if it needs to individually place the blocks

Hm, ok than

**Comment by jumboman32** [comment] 2021-06-26 22:58
Use the format next time

**Comment by HarryPotter42MC** [comment] 2021-06-28 08:46
I think hes talking about something like HighwayTools

**Comment by browsky300** [comment] 2022-09-01 05:20
duplicate of #411

**Closed by browsky300** 2022-09-01 05:20 UTC
Labels: enhancement, module-enhancement
