### ISSUE TITLE
[FEATURE] swap delay under autotool

### ISSUE THREAD

**Issue by Badinek** [John200410/rusherhack-issues#158] opened 2020-11-17 15:47 UTC
**What feature would you like to be added.**
Swap delay under autotool module- customizable delay between switching tools 

**Is your feature request related to a problem? Please describe.**
sometimes it swaps the item too fast and it doesnt let me break the block. means autotool doesnt work half the time

**Comment by John200410** [comment] 2020-11-20 01:47
Thank you for the suggestion.

**Comment by John200410** [comment] 2020-11-22 23:08
Can you record a video of it not working?

**Comment by John200410** [comment] 2020-11-28 08:10
Cannot reproduce the problem. Closing issue

**Closed by John200410** 2020-11-28 08:10 UTC
Labels: enhancement
