### ISSUE TITLE
cloud config system and an UPDATE

### ISSUE THREAD

**Issue by teejwrld** [John200410/rusherhack-issues#1274] opened 2022-04-04 11:09 UTC
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
people can upload a config to a discord bot or something and you can see it in one of the windows, some 1.8 clients have it
**Is your feature request related to a problem? Please describe.**
no
no
**Additional context**
![image](https://user-images.githubusercontent.com/85442181/161531400-5445260d-a7a3-44b3-859e-eb9779151622.png)
in one of these windows

**Comment by HausemasterIssue** [comment] 2022-04-04 12:59
I prefer to minimize connections to 3rd party websites when playing. If you do add this, please add an option to toggle it on and off.

**Comment by Ozynt** [comment] 2022-04-04 13:05
John has planned to add a cloud config system and he probably make an option to turn it off. 
Duplicate of #189

**Closed by Ozynt** 2022-04-04 13:05 UTC
Labels: enhancement

**Comment by Mathrandom7910** [comment] 2022-04-04 19:27
> i prefer you to shut the fuck up

Getting angry over a suggestion lol

**Comment by teejwrld** [comment] 2022-04-04 21:51
no one is talking to you 💀💀

**Comment by TwoThreeTwo** [comment] 2022-04-05 20:00
bbg, just stop responding, you aren't going to get any pleasure out of this
