### ISSUE TITLE
[FEATURE] IllegalNotifier

### ISSUE THREAD

**Issue by yiqitozturk** [John200410/rusherhack-issues#288] opened 2021-01-01 08:28 UTC
**What feature would you like to be added.**
Shows a notification when you find bedrock where it shouldn't be (y5-y124 in nether/y5> in overworld) .
Shows a notification when you find water in nether.

**Comment by John200410** [comment] 2021-01-04 05:46
Duplicate of #228

**Closed by John200410** 2021-01-04 05:46 UTC
Labels: duplicate, enhancement
