### ISSUE TITLE
[FEATURE] ChestSwap

### ISSUE THREAD

**Issue by 453452hw** [John200410/rusherhack-issues#947] opened 2021-07-16 20:08 UTC
**What feature would you like to be added.**
Chestswap: When activated swaps your chestplate with your elytra or your elytra with your chestplate.

**Comment by abt5** [comment] 2021-07-16 22:12
im pretty sure you can make a macro for that

**Comment by abt5** [comment] 2021-07-16 22:12
as in rusherhacks macro command

**Comment by 453452hw** [comment] 2021-07-16 22:25
if you know the macro. send me it but i dont know if thats possible with a macro

**Comment by abt5** [comment] 2021-07-16 22:34
*macro add (key) autoarmor elytra_priority

**Comment by jumboman32** [comment] 2021-07-16 23:52
Duplicate of #853.  (or use macro)

**Closed by jumboman32** 2021-07-16 23:52 UTC
Labels: enhancement
