### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by icpvpbadly** [John200410/rusherhack-issues#1143] opened 2021-11-27 12:26 UTC
**What feature would you like to be added.**
add a working bowbomb and make it seperate from bowspam and shader chams

**Is your feature request related to a problem? Please describe.**
for the shader chams no its not a problem, but the bowbomb inside bowspam doesnt work at all

**Additional context**
i love you john

**Comment by John200410** [comment] 2021-11-27 18:03
BowBomb is patched on 2b2t.

Rest is duplicate of #1140

**Closed by John200410** 2021-11-27 18:03 UTC
Labels: enhancement
