### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by 2u9** [John200410/rusherhack-issues#1333] opened 2022-07-31 08:53 UTC
**What feature would you like to be added.**
Custom image uploader for ExtraScreenshot

**Is your feature request related to a problem? Please describe.**
Personally I dont like my screenshots being uploaded to Imgur, but I dont know how hard would this be to implement like ShareX has it

**Additional context**

**Comment by Ozynt** [comment] 2022-07-31 10:38
Duplicate of #90

**Closed by Ozynt** 2022-07-31 10:38 UTC
Labels: enhancement
