### ISSUE TITLE
[FEATURE] Double HoleESP / DoubleHoleTP 

### ISSUE THREAD

**Issue by Floppinqq** [John200410/rusherhack-issues#305] opened 2021-01-04 15:30 UTC
add Double option in hole esp and add holetp with double option (to be in middle of a hole with 2 blocks at X)

**Comment by ToxicAven** [comment] 2021-01-05 17:06
#184 Covers the HoleESP Part

**Comment by John200410** [comment] 2021-01-09 17:06
I don't plan on adding hole tp since reverse step does the same thing. Considering this as a duplicate of #184

**Closed by John200410** 2021-01-09 17:06 UTC
Labels: duplicate, enhancement
