### ISSUE TITLE
[FEATURE] Hand Chams Shader Chams And Sliding rgb

### ISSUE THREAD

**Issue by adabugra** [John200410/rusherhack-issues#1382] opened 2022-10-11 16:55 UTC
**What feature would you like to be added.**
Hand chams crystal chams player chams with wireframe mod and sliding rgb
![154330928-7e524849-e278-4cd6-8a71-3d895e74c004](https://user-images.githubusercontent.com/57899270/195153385-c8a84468-ab59-4fd1-870a-3d46f276a369.png)
Also shader chams

**Comment by browsky300** [comment] 2022-10-12 03:39
duplicate of #1140

**Closed by browsky300** 2022-10-12 03:39 UTC
Labels: enhancement
