### ISSUE TITLE
[FEATURE] Offline Mode "Alt" Support

### ISSUE THREAD

**Issue by clockwork04** [John200410/rusherhack-issues#296] opened 2021-01-02 21:26 UTC
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

The ability to use offline mod accounts on offline mode servers using the alt manager

**Is your feature request related to a problem? Please describe.**

Having to restart minecraft to just use a different offline mode username is bloody annoying

**Comment by John200410** [comment] 2021-01-04 06:11
Duplicate of #64

**Closed by John200410** 2021-01-04 06:11 UTC
Labels: enhancement
