### ISSUE TITLE
[FEATURE] Step vanilla mode

### ISSUE THREAD

**Issue by Mishi04** [John200410/rusherhack-issues#509] opened 2021-03-07 18:00 UTC
**What feature would you like to be added.**
Add a vanilla mode for step. this would be useful for servers like us.crystalpvp.cc where step only works in vanilla mode

**Is your feature request related to a problem? Please describe.**
I practice pvp on servers where only step works in vanilla mode and I have to use another client just for that module

**Additional context**
N/A

**Comment by jennifer-uwu** [comment] 2021-03-08 12:27
ncp mode works on vanilla servers

**Comment by John200410** [comment] 2021-03-23 12:28
Duplicate of #92

**Closed by John200410** 2021-03-23 12:28 UTC
Labels: enhancement
