### ISSUE TITLE
[BUG] rendering issue

### ISSUE THREAD

**Issue by queenellee** [John200410/rusherhack-issues#1316] opened 2022-06-27 08:50 UTC
I have encountered a bug where if I die on certain minecraft servers e.g. crystalpvp.cc, 2b2tpvp.org I will just have a rendering issue where I only see a white screen and if I press esc it will turn blue, this only happens on rusherhack and I don't know what to do

For this to happen I just need to die in one of those servers.

Other mods I am using are: Schematica, Family Fun Pack, Journey Map and Shulker Box Viewer

What should happen is that I respawn at the respawn point and should be able to see like normal rather than a white or blue screen

![image_2022-06-27_094940238](https://user-images.githubusercontent.com/107427255/175899382-12e53cb5-c593-4c30-8b02-4eae69467c7b.png)
![image_2022-06-27_095025167](https://user-images.githubusercontent.com/107427255/175899524-c33d0a54-742e-40f0-9f09-ce1da878912e.png)

Thank You

**Comment by HausemasterIssue** [comment] 2022-06-27 14:14
This is caused by the current version of RusherHack's 'Outline' ESP. In order to fix this bug, switch ESP to a different mode like 'Shader' or 'CsGo', or just turn it off altogether. This bug is fixed in the next version of RusherHack, it's release is pending though. You can get RusherHack+ to get access to unreleased updates.

**Comment by Ozynt** [comment] 2022-07-06 15:00
Is this fixed?

**Comment by HausemasterIssue** [comment] 2022-07-06 15:45
I am not sure. In the issue John has never said it is fixed nor closed it at all, so unlikely. Check the RusherHack v1.3 changelog.

**Comment by browsky300** [comment] 2022-07-22 19:10
This is an issue with ESP's Outline mode. It will be fixed, but in the meantime you can choose the Shader mode.

**Comment by browsky300** [comment] 2022-07-22 19:10
also closing since there are already a few other issues of this

**Closed by browsky300** 2022-07-22 19:10 UTC
Labels: bug
